# -*- coding: utf-8 -*-
"""__init__.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11DBn9Q1vdZDtCmN5Ow-wBgnQlIgfxCsC
"""

from .core import DataWrangler, InsightVisualizer