# -*- coding: utf-8 -*-
"""Setup.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10besnUZywx3QmYxwvTPVcv-jlCKapsKg
"""

from setuptools import setup, find_packages

setup(
    name='data_wrangler',
    version='0.1.0',
    description='A modular data sanitization and exploration engine.',
    author='Your Name', # Put your name here
    packages=find_packages(),
    install_requires=[
        'pandas',
        'numpy',
        'scipy',
        'plotly',
        'scikit-learn',
        'ipython'
    ],
)